Revision of the navbar using Json data to keep the code readable
USUGraffix/client pull request #193
Opened 2021-02-11 19:40 UTC by StewartMckenzie

2021-02-12 19:35 UTC, DandyReyes requested changes

2021-02-12 19:35 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +  const [clicked, setClicked] = useState(false);
What does setClicked do...? May you choose a more descriptive name for this variable please.

2021-02-12 19:35 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +  const [clicked, setClicked] = useState(false);
I don't mind if the variable name is long too, readability over cleverness :)

2021-02-12 19:35 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +          mobileNavRef.current &&
This if statement and the if statement on line 41 do the same functionality. Make this a re-usable function.

2021-02-12 19:35 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +                    {linkData.firstLevel && (
This variable name "firstLevel" and "secondLevel" is a bit confusing Please choose a more descriptive name. Just think about you coming back after 20 years to maintain this code or a super young developer maintaining this code.

2021-02-12 19:35 UTC, DandyReyes commented on src/components/Navbar/linksData.js
> +export const navLinkData = [
lmao, I just wanted a JSON file but you made a JS file instead. It works all the same. Good job.

2021-02-12 19:35 UTC, DandyReyes commented on src/scss/Navbar.scss
> +  z-index: 2;
Why is this on the second z-index? I think the first z-index would be sufficient unless something strange happens at that level.

2021-02-12 19:35 UTC, DandyReyes commented on src/scss/Navbar.scss
> +  display: flex;
I don't think this does anything.

2021-02-12 19:35 UTC, DandyReyes commented on src/scss/Navbar.scss
> +  font-size: 35px;
Make this font-size into a variable please. I see it re-used a couple time already.

2021-02-12 19:35 UTC, DandyReyes commented on src/scss/Navbar.scss
> +    color: gold;
All color should be in a variable. Unless this is the ONLY place you use it.

2021-02-17 19:33 UTC, DandyReyes requested changes

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +  const [menuActivated, setMenuActivated] = useState(false);
For lines 9 to 11, make it into one using state and setState. It just helps consolidate and keep your code cleaner.
```js
const [state, setState] = useState({menuActivated: false, navItemExpanded: false, expandedItem: 
''});
```

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +      setMenuActivated(false);
when you switch the top code with [state, setState], you could write code that's more concise with 
```js
setState({menuActivated: false, navItemExpanded: false});
```

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +          setMenuActivated(false);
Same as previous comment about setState

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +          <div
navLinkData can be destructured. Remember readability!
```js
const { links, nestedLinks, socialLinks } = navLinkData;
```
Also, please use a more descriptive variable than nestedLinks. Please and thank you.

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +                      </div>
linkData can be destructured with name, class, link. Please use a more descriptive variable for firstLevel. It's a bit confusing.

2021-02-17 19:33 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +                      </div>
destructure, destructure, destructure! also, need a more descriptive name than secondLevel please.

2021-02-18 19:32 UTC, StewartMckenzie commented on src/scss/Navbar.scss
> +  display: flex;
Removed

2021-02-18 19:33 UTC, StewartMckenzie commented on src/scss/Navbar.scss
> +  font-size: 35px;
Updated

2021-02-18 19:36 UTC, StewartMckenzie commented on src/scss/Navbar.scss
> +    color: gold;
Updated

2021-02-18 19:37 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +  const handleMobileMenu = () => {
Removed

2021-02-18 19:55 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +          <div
Updated

2021-02-18 20:10 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +  const [clicked, setClicked] = useState(false);
Updated

2021-02-18 20:10 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +  const [menuActivated, setMenuActivated] = useState(false);
Updated

2021-02-18 20:10 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +      setMenuActivated(false);
Updated

2021-02-18 20:20 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +          setMenuActivated(false);
Updated

2021-02-18 20:20 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +          <div
Updated

2021-02-18 20:20 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +                      </div>
Updated

2021-02-18 20:20 UTC, StewartMckenzie commented on src/components/Navbar/Navbar.js
> +                      </div>
Updated

2021-02-18 20:47 UTC, DandyReyes requested changes

2021-02-18 20:47 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +          {!state.navItemExpanded && (
you can destructure this as well.
```js
const {navItemExpanded, menuActivated, expandedItem} = state;
```

2021-02-18 20:47 UTC, DandyReyes commented on src/components/Navbar/Navbar.js
> +          {!state.navItemExpanded && (
anywhere that you see

`state`.someVariableName can be destructured

2021-02-19 21:52 UTC, DandyReyes requested changes

2021-02-19 21:52 UTC, DandyReyes commented on src/scss/Navbar.scss
> +  font-size: 25px;
Please use scss variable for ALL the font sizes. I rather change one variable than 20 places on the scss file. Makes our code maintainable. I've seen 25, 30, 35 and 1.8rem size font.

2021-02-22 16:42 UTC, merged