-Added background color for department card component -Improved respo…
USUGraffix/client pull request #200
Opened 2021-03-22 21:24 UTC by pgatsby

…nsiveness for mobile view -Removed image from mobile view -Made button accessible in mobile view

2021-03-23 18:03 UTC, DandyReyes requested changes

2021-03-23 18:03 UTC, DandyReyes commented on src/scss/DepartmentsPage.scss
> +          height: 100%;
What happens with this element when you collapse it vertically OR horizontally? Let's avoid distortions in our images. If there is no distortion then ignore this comment.

2021-03-23 18:03 UTC, DandyReyes commented on src/scss/DepartmentsPage.scss
>        }
Is this missing a curly brace? Also, this is a bit overkill in terms of targeting an element if you are not styling departmentsCard or departmentsCardContent. You could just go straight to departmentsCardDesc if you aren't using those.

2021-03-26 00:08 UTC, DandyReyes requested changes

2021-03-26 00:08 UTC, DandyReyes commented on src/components/DepartmentsPage/DepartmentsPage.js
> +const Card = ({ id, title, desc, link, img, imgAlt }) => {
This seems like a component so if it is, make sure to create another component on this file called Card.js
Then use props to pass the data.

2021-03-26 00:08 UTC, DandyReyes commented on src/components/BasicTemplate/BasicTemplatePage.js
> +          <p>{page.desc}</p>
Destructure this further. Create a variable and use that before the return statement.

2021-03-26 00:08 UTC, DandyReyes commented on src/components/BasicTemplate/BasicTemplatePage.js
> +const BasicTemplatePage = ({ data, ...page }) => {
Again, you can use

```js
export default const BasicTemplatePage = () => {
```

2021-03-26 00:08 UTC, DandyReyes commented on src/components/BasicTemplate/BasicTemplatePage.js
> +const BasicTemplatePage = ({ data, ...page }) => {
Can you more descriptive than just `data`. All about readability. The variable name can be long as well if you're thinking about that.

2021-03-26 00:08 UTC, DandyReyes commented on src/components/DepartmentPage/DepartmentPage.js
> +      data={departmentsData.data}
DESTRUCTURE!

2021-03-26 00:08 UTC, DandyReyes commented on src/components/BasicTemplate/BasicTemplatePage.js
> +const Card = ({ id, title, desc, link, img, imgAlt }) => {
Make this another component.

2021-03-30 17:43 UTC, DandyReyes requested changes

2021-03-30 17:43 UTC, DandyReyes commented on src/components/DepartmentPage/DepartmentsData.js
> +  pageInfo: [
This could be a bit more of a descriptive variable name. Perhaps something like `departmentInfo`, pageInfo is ambiguous.

2021-04-06 23:20 UTC, StewartMckenzie approved these changes

2021-04-06 23:20 UTC, merged